import { Project } from "@/types";

export const projects: Project[] = [
  {
    name: "A Pay as You Watch Platform (LOGERS.WATCH)",
    description:
      "A Web3 watch-to-earn platform where viewers deposit tokens on-chain, pay as they stream video content, and creators claim earnings on-chain using Merkle proofs generated by the backend.",
    github: "https://github.com/Atul-ThakreLO/Logers.Watch",
    url: undefined,
    category: "web3",
    techStack: ["Solidity", "Foundry", "Bun", "Elysia", "PSQL", "Redis", "Next.js", "Merkle Trees", "Typescript"],
  },
  {
    name: "A Fitquest: NFT, NFT-MarketPlace & Auction",
    description:
      "A complete Web3 DApp for minting, trading, and auctioning Territory NFTs on the Base network. Built with a modern monorepo architecture, it features a Next.js frontend, an Elysia-powered backend API with Redis caching, and robust Foundry-tested smart contracts.",
    github: "https://github.com/Atul-ThakreLO/fitquest-nfy-marketplace",
    url: undefined,
    category: "web3",
    techStack: ["Solidity", "Next.js", "Elysia", "Redis", "Base"],
  },
  {
    name: "A Cross Chain Rebase Token",
    description:
      "A Solidity-based rebase token with cross-chain capabilities using Chainlink CCIP (Cross-Chain Interoperability Protocol). This project implements an interest-bearing token that automatically accrues value over time and can be transferred across different blockchain networks.",
    github: "https://github.com/Atul-ThakreLO/Cross-Chain-Rebase-Token",
    url: undefined,
    category: "web3",
    techStack: ["Solidity", "Chainlink CCIP", "Foundry", "Smart Contracts"],
  },
  {
    name: "A Decentralized Stable Coin",
    description:
      "A decentralized, algorithmic stablecoin system pegged to USD, built with Solidity and Foundry. This project implements a fully collateralized stablecoin protocol with exogenous, decentralized, anchored (pegged), crypto-collateralized low-volatility coin designed to maintain a 1:1 peg with the US Dollar.",
    github: "https://github.com/Atul-ThakreLO/Decentralized-Stable-Coin",
    url: undefined,
    category: "web3",
    techStack: ["Solidity", "Foundry", "Algorithmic Tokenomics"],
  },
  {
    name: "Airdrop (Bagel Token)",
    description:
      "This project implements a Merkle Tree-based airdrop system that allows eligible users to claim ERC20 tokens (BagelToken) efficiently. The system uses cryptographic proofs to verify eligibility and supports meta-transactions for gasless claims via EIP-712 signatures.",
    github: "https://github.com/Atul-ThakreLO/Airdrop-Merkel-Tree",
    url: undefined,
    category: "web3",
    techStack: ["Solidity", "EIP-712", "Merkle Tree", "Foundry"],
  },
  {
    name: "Academy management frontend",
    description:
      "A responsive, role-based frontend built with React.js, Tailwind CSS, and Vite, designed to support public users, students, and staff across educational institutions. The interface emphasizes usability, performance, and smooth content interaction.",
    github: "https://github.com/Atul-ThakreLO/target-academy",
    url: "https://target-academy-6bl9.vercel.app",
    category: "fullstack",
    techStack: ["React.js", "Tailwind CSS", "Vite", "TypeScript"],
  },
  {
    name: "Academy management backend",
    description:
      "A secure and scalable backend developed using Node.js, Express, and Prisma ORM, powered by Supabase (PostgreSQL). It manages authentication, academic workflows, file handling, and email communication through a robust API architecture.",
    github: "https://github.com/Atul-ThakreLO/target-aws",
    url: undefined,
    category: "fullstack",
    techStack: ["Node.js", "Express", "Prisma ORM", "Supabase", "PostgreSQL"],
  },
  {
    name: "Portfolio",
    description:
      "A stunning, performant portfolio website built with Next.js 16, featuring smooth animations, interactive components, and SEO optimization. This portfolio showcases projects, skills, and professional experience with a modern, engaging user interface.",
    github: "https://github.com/Atul-ThakreLO/portfolio",
    url: "https://atul-thakre-portfolio.vercel.app/",
    category: "frontend",
    techStack: ["Next.js", "Tailwind CSS", "GSAP", "TypeScript"],
  },
  {
    name: "Books inventory (GraphQL)",
    description:
      "This is Simple graphql server to utilize the power of graphql. This is a simple backend for managing book and their Authors, I used the graphql server to take hands on experiance of graphql by building this project",
    github: "https://github.com/Atul-ThakreLO/graphql-server",
    url: undefined,
    category: "backend",
    techStack: ["GraphQL", "Node.js", "Apollo Server", "TypeScript"],
  },
  {
    name: "CLI Tool - Section Comment",
    description:
      "A fast and efficient CLI tool for generating beautifully formatted section comments in your code. No more manually typing repetitive comment blocks - just run one command and get professional-looking section dividers instantly copied to your clipboard.",
    github: "https://github.com/Atul-ThakreLO/CLI-Tool-section-comment",
    url: undefined,
    category: "other",
    techStack: ["TypeScript", "Node.js CLI", "Chalk"],
  },
  {
    name: "Upsurge2k25",
    description:
      "A dynamic tech fest website for UPSURGE 2K25, the annual CSE tech fest of YCCE. Built using Next.js and enhanced with GSAP animations to deliver a fast, interactive, and visually engaging experience.",
    github: "https://github.com/Atul-ThakreLO/upsurge2k25",
    url: "https://upsurge2k25.vercel.app/",
    category: "frontend",
    techStack: ["Next.js", "GSAP", "Tailwind CSS"],
  },
  {
    name: "YCCExMUN CSE",
    description:
      "A dynamic and visually engaging website for MUN, the debate competition by YCCE (CSE). Developed using Next.js and GSAP, focusing on smooth animations, responsiveness, and a professional event presence.",
    github: "https://github.com/Atul-ThakreLO/yccexmun",
    url: "https://yccexmun-dev.vercel.app",
    category: "frontend",
    techStack: ["Next.js", "GSAP", "Tailwind CSS"],
  },
  {
    name: "BlockMind",
    description: "Crop suggestions, disease detection using blockchain and AI.",
    github: "https://github.com/Atul-ThakreLO/BlockMind",
    url: undefined,
    category: "fullstack",
    techStack: ["ML", "AI", "Python"],
  },
];

export interface Experience {
  role: string;
  company: string;
  type: string;
  period: string;
  location: string;
  bullets: string[];
}

export const experiences: Experience[] = [
  {
    role: "Web Master",
    company: "YCCE College Events",
    type: "Volunteer",
    period: "2024 – 2026",
    location: "Nagpur, India",
    bullets: [
      "Led frontend development for Upsurge2K25 and YCCExMUN — tech fest and MUN websites.",
      "Implemented GSAP animations and optimized performance for high-traffic event periods.",
      "Collaborated with design teams to deliver pixel-perfect, responsive UIs.",
    ],
  },
  {
    role: "Full Stack Developer",
    company: "Freelance / Open Source",
    type: "Self-Employed",
    period: "2023 – Present",
    location: "Remote",
    bullets: [
      "Built production-ready Fullstack applications.",
      "Developed full-stack applications with Node, Express, React, TypeScript.",
      "Contributed to and maintained open-source repositories.",
    ],
  },
  {
    role: "Web3 & Full Stack Developer",
    company: "Freelance / Open Source",
    type: "Self-Employed",
    period: "2024 – Present",
    location: "Remote",
    bullets: [
      "Built production-ready DeFi protocols, cross-chain token systems and airdrop mechanisms using Solidity & Foundry.",
      "Developed full-stack dApps with Next.js, TypeScript, and Ethereum integrations.",
      "Contributed to and maintained open-source smart contract repositories.",
    ],
  },
];
